# Generated by Django 5.1.4 on 2026-07-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttributeRegistry",
            fields=[
                ("attr_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("canonical_name", models.CharField(max_length=64, unique=True)),
                ("source", models.CharField(max_length=255)),
                ("is_filterable", models.BooleanField(default=True)),
                ("is_dimension", models.BooleanField(default=True)),
                ("data_type", models.CharField(max_length=32)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "attribute_registry",
            },
        ),
        migrations.CreateModel(
            name="DimBrand",
            fields=[
                ("brand_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("brand_code", models.CharField(max_length=32, unique=True)),
                ("brand_name", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dim_brand",
            },
        ),
        migrations.CreateModel(
            name="DimCalendar",
            fields=[
                ("date_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(unique=True)),
                ("day", models.PositiveSmallIntegerField()),
                ("month_no", models.PositiveSmallIntegerField()),
                ("month_name", models.CharField(max_length=16)),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        help_text="Fiscal quarter: Apr-Jun=1 .. Jan-Mar=4"
                    ),
                ),
                (
                    "financial_year",
                    models.CharField(help_text="e.g. '23-24', Apr-Mar", max_length=8),
                ),
            ],
            options={
                "db_table": "dim_calendar",
            },
        ),
        migrations.CreateModel(
            name="DimSeason",
            fields=[
                ("season_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("season_code", models.CharField(max_length=64, unique=True)),
                ("season_type", models.CharField(blank=True, max_length=32, null=True)),
                ("season_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "dim_season",
            },
        ),
        migrations.CreateModel(
            name="BrandUploadConfig",
            fields=[
                ("config_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_line", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=128)),
                ("column_map", models.JSONField()),
                ("date_source", models.CharField(max_length=64)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_configs",
                        to="masterdata.dimbrand",
                    ),
                ),
            ],
            options={
                "db_table": "brand_upload_config",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "product_line"), name="uniq_brand_product_line_config"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DimProduct",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("barcode", models.CharField(max_length=64)),
                ("article_code", models.CharField(blank=True, max_length=128, null=True)),
                ("category", models.CharField(blank=True, max_length=128, null=True)),
                ("sub_category", models.CharField(blank=True, max_length=128, null=True)),
                ("gender", models.CharField(blank=True, max_length=32, null=True)),
                ("fit", models.CharField(blank=True, max_length=64, null=True)),
                ("color", models.CharField(blank=True, max_length=64, null=True)),
                ("size", models.CharField(blank=True, max_length=32, null=True)),
                ("print_type", models.CharField(blank=True, max_length=64, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="masterdata.dimbrand",
                    ),
                ),
            ],
            options={
                "db_table": "dim_product",
                "constraints": [
                    models.UniqueConstraint(fields=("brand", "barcode"), name="uniq_brand_barcode")
                ],
            },
        ),
        migrations.CreateModel(
            name="DimStore",
            fields=[
                ("store_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("store_code", models.CharField(max_length=32)),
                ("store_name", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=128, null=True)),
                ("state", models.CharField(blank=True, max_length=128, null=True)),
                ("zone", models.CharField(blank=True, max_length=64, null=True)),
                ("store_type", models.CharField(blank=True, max_length=64, null=True)),
                ("distributor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stores",
                        to="masterdata.dimbrand",
                    ),
                ),
            ],
            options={
                "db_table": "dim_store",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("brand", "store_code"), name="uniq_brand_store_code"
                    )
                ],
            },
        ),
    ]
