# Generated by Django 5.1.4 on 2026-07-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_create_fact_sales"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                ("batch_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(max_length=255)),
                ("object_key", models.CharField(max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("parsing", "Parsing"),
                            ("validating", "Validating"),
                            ("failed", "Failed"),
                            ("loaded", "Loaded"),
                            ("rolled_back", "Rolled back"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("row_count", models.IntegerField(blank=True, null=True)),
                ("error_count", models.IntegerField(blank=True, null=True)),
                ("slices", models.JSONField(blank=True, default=list)),
                ("error_report_key", models.CharField(blank=True, max_length=512, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to="masterdata.dimbrand",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to="masterdata.branduploadconfig",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upload_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upload_batch",
            },
        ),
    ]
