# Generated by Django 5.1.4 on 2026-07-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0003_link_fact_sales_upload_batch_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadbatch",
            name="failure_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
