# Generated by Django 5.1.4 on 2026-07-05 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0004_uploadbatch_failure_reason"),
        ("masterdata", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadbatch",
            options={
                "permissions": [
                    (
                        "alter_existing_data",
                        "Can replace or roll back sales data that is already loaded",
                    )
                ]
            },
        ),
        migrations.CreateModel(
            name="DataAlterationAudit",
            fields=[
                ("audit_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("replace", "Replace existing slice(s)"),
                            ("rollback", "Roll back batch"),
                        ],
                        max_length=16,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("allowed", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alteration_audits",
                        to="ingestion.uploadbatch",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="masterdata.dimbrand"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alteration_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "data_alteration_audit",
            },
        ),
    ]
