# Generated by Django 5.1.4 on 2026-07-18 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0005_alter_uploadbatch_options_dataalterationaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataalterationaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("replace", "Replace existing slice(s)"),
                    ("rollback", "Roll back batch"),
                    ("delete_filtered", "Delete by brand/product line/month/year filter"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="dataalterationaudit",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alteration_audits",
                to="ingestion.uploadbatch",
            ),
        ),
    ]
